CafeMan-Project/Models/Entities/Favourite.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CafeMan_Project.Models.Entities
{
    public class Favourite
    {
        public int FavouriteId { get; set; }
        public User User { get; set; }
        public Cafe Cafe { get; set; }
        public int CafeId { get; set; }
    }
}

CafeMan-Project/Controllers/CafemanController.cs
using CafeMan_Project.Models.Entities;
using CafeMan_Project.Models.ViewModels;
using CafeMan_Project.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CafeMan_Project.Controllers
{
    public class CafemanController : Controller
    {
        private readonly ICafeRepository<Cafe> cafeRepo;

        public CafemanController(ICafeRepository<Cafe> cafeRepo)
        {
            this.cafeRepo = cafeRepo;
        }


        
        public IActionResult Cafeman(string id)
        {
            ViewBag.Title = "کافه من";
            var model = new CafemanVM()
            {
                ID =id
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Cafeman(CafemanVM model)
        {
            if (ModelState.IsValid)
            {
                var cafe = new Cafe()
                {
                    CafeName = model.CafeName,
                    CafeDescription = model.CafeDescription,
                    Tel = model.Tel,
                    Address = model.Address,
                    Website = model.Website,
                    Location = model.Location,
                    PriceRange = model.PriceRange,
                    Details = model.Details,
                };

                await cafeRepo.Insert(cafe);

                HttpContext.Response.Cookies.Append("usi", model.ID);

                return RedirectToAction("HomeAccount", "Home");
            }

            return View(model);
        }
    }
}

CafeMan-Project/Controllers/FavouriteController.cs
using CafeMan_Project.Models.Dal;
using CafeMan_Project.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CafeMan_Project.Controllers
{
    [Authorize("Roles")]
    public class FavouriteController : Controller
    {
        private readonly CafemanDbContext ctx;
        private readonly UserManager<User> userManager;

        public FavouriteController(CafemanDbContext ctx,UserManager<User> userManager)
        {
            this.ctx = ctx;
            this.userManager = userManager;
        }

        [Route("Favourite/List")]
        public async Task<IActionResult> Favourite()
        {
            ViewBag.Title = "علاقه مندی ها";

            User user;
            if(TempData.Peek("userId") != null)
                user = await userManager.FindByIdAsync(TempData.Peek("userId").ToString());
            else
                return RedirectToAction("SignIn", "SignIn");


            return View(user);
        }
    }
}

CafeMan-Project/Controllers/RankingController.cs
using CafeMan_Project.Models.Entities;
using CafeMan_Project.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CafeMan_Project.Controllers
{
    public class RankingController : Controller
    {
        private readonly ICafeRepository<Cafe> cafe;

        public RankingController(ICafeRepository<Cafe> cafe)
        {
            this.cafe = cafe;
        }

        [Route("Ranking/List")]
        public async Task<IActionResult> Ranking()
        {
            ViewBag.Title = "رنکینگ";
            var cafes = await cafe.GetAll();//.OrderByDescending(c=>c.Star);
            
            return View(cafes);
        }
    }
}

CafeMan-Project/Views/Favourite/Favourite.cshtml
@section style{
    <link rel="stylesheet" href="~/Assets/css/favourite.css">
}

@section script {
    <script src="~/Assets/js/like.js"></script>
    <script src="~/Assets/js/search-click.js"></script>
}



<header>
    <p>CafeMan</p>
    <nav>
        <div>
            <a asp-controller="Ranking" asp-action="Ranking">رنکینگ</a>
            <a asp-controller="Cafeman" asp-action="Cafeman">کافه من</a>
            <a asp-controller="Favourite" asp-action="Favourite">علاقه مندی ها</a>
        </div>
        <div style="display:none" class="search-nav">
            <img width="15" height="15" src="https://img.icons8.com/ios-filled/15/search--v1.png" alt="search--v1" />
            <input type="text" placeholder="کافه مورد نظرتو پیدا کن">
            <button href=""><div></div><div></div></button>
        </div>
        <div style="display:none">
            <a href="signin.html">ورود</a>
            <a href="signup.html">ثبت نام</a>
        </div>
    </nav>
</header>

<main>

    <div class="category">
        <p>دسته بندی بر اساس :</p>
        <div class="ctg">
            <a href="">رتبه</a>
            <a href="">قیمت</a>
            <a href="">باز بودن</a>
        </div>

    </div>

    <div class="cafes">

        @if(Model.Favourites != null)
        {

            @foreach (var fav in Model.Favourites)
            {
                <div class="cafe-card">
                    <img src="~/Assets/Images/Profile/behtarin-coffee-shop-shike-tehran.jpg" alt="Cafe Image">
                    <div class="cafe-details">
                        <div><h3><a href="">@fav.Cafe.CafeName</a><samp id="rank">1#</samp></h3><a class="unsave"><img width="25" height="25" src="https://img.icons8.com/ios-glyphs/25/hearts.png" alt="hearts" /></a><a class="save"><img width="25" height="25" src="https://img.icons8.com/color/25/filled-like.png" alt="filled-like" /></a></div>
                        <p class="des">@fav.Cafe.CafeDescription</p>
                    </div>
                </div>
            }

        }
        else
        {
            <p style="font-size:xx-large; color:brown">شما هنوز کافه مورد علاقه ای ندارید</p>
        }

 @*        <div class="cafe-card cafe1">
            <img src="~/Assets/Images/Profile/behtarin-coffee-shop-shike-tehran.jpg" alt="Cafe Image">
            <div class="cafe-details">
                <div><h3><a href="">کافه کارا</a><samp id="rank">1#</samp></h3><a class="unsave"><img width="25" height="25" src="https://img.icons8.com/ios-glyphs/25/hearts.png" alt="hearts" /></a><a class="save"><img width="25" height="25" src="https://img.icons8.com/color/25/filled-like.png" alt="filled-like" /></a></div>
                <p class="des">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
            </div>
        </div> *@



    </div>

</main>